name: Bump version

on:
  pull_request:
    types:
      - closed    

jobs:
  bump-version:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump-version.outputs.tag }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: version-tag
        id: tag
        uses: ./.github/action
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: master
          
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [bump-version]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }} 
        with:
         tag_name: ${{ needs.bump-version.outputs.version }}
         release_name: ${{ needs.bump-version.outputs.version }}     
