name: Bump version

on:
  pull_request:
    types:
      - closed    

jobs:
  Create-Tag:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    name: Create-Tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.Create-Tag.outputs.tag }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Set branch check variable
        id: branch_check
        run: |
          if [ "$GITHUB_REF" == "refs/heads/master" ] || [ "$GITHUB_REF" == "refs/heads/develop" ]; then
            echo "Branch is master or develop"
            echo "::set-output name=branch_match::true"
          else
            echo "Branch is not master or develop"
            echo "::set-output name=branch_match::false"
          fi 

      - name: Display result
        run: |
          branch_match="${{ steps.branch_check.outputs.branch_match }}"
          echo "Branch match: $branch_match"   

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install semver CLI
        run: npm install -g semver

      - name: Get version bump type
        id: get_version_bump
        run: |
          # Extract labels from pull request using jq
          labels=$(jq -r '.pull_request.labels[].name' $GITHUB_EVENT_PATH)
          echo "Extracted Labels: $labels"

          # Determine version bump type based on labels
          if echo "$labels" | grep -q 'major'; then
            echo "major"
          elif echo "$labels" | grep -q 'minor'; then
            echo "minor"
          elif echo "$labels" | grep -q 'patch'; then
            echo "patch"
          else
            echo "none"
          fi  

      - name: Print event details
        run: cat $GITHUB_EVENT_PATH    

      - name: Set custom branch suffix
        id: set_suffix
        run: echo "::set-output name=suffix::ppr"

      - name: Set MAJOR STRING TOKEN
        id: set_MAJOR_STRING
        run: echo "::set-output name=major::major"    

      - name: version-tag
        id: Create-Tag
        uses: ./.github/action
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: master
          PRERELEASE: true
          PRERELEASE_SUFFIX: ${{ steps.set_suffix.outputs.suffix }}
          MAJOR_STRING_TOKEN: ${{ steps.set_MAJOR_STRING.outputs.major }}
          DRY_RUN: true
          
  Create-Release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [Create-Tag]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }} 
        with:
         tag_name: ${{ needs.Create-Tag.outputs.version }}
         release_name: ${{ needs.Create-Tag.outputs.version }} 

      - name: Upload release binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN  }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}    
