name: Bump version

on:
  pull_request:
    types:
      - closed    

jobs:
  bump-version:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: version-tag
        id: tag
        uses: ./.github/action/github-tag-action
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: master
